services:
  docs:
    image: python:3.13.1-alpine@sha256:5dad625efcbc6fad19c10b7b2bfefa1c7a8129c8f8343106b639c27dd9e7db2c
    entrypoint: [ ]
    command: sh -c "cd docs && pip install -r requirements.txt && mkdocs serve --dev-addr=0.0.0.0:8000"
    volumes:
      - .:/docs
    ports:
      - 8000:8000
