services:
  docs:
    image: python:3.14.4-alpine3.22@sha256:355522f4e6b640e9255e6b6830ef52f32ece54df43db93f61101f48c5d4c6658
    entrypoint: [ ]
    command: sh -c "cd docs && pip install -r requirements.txt && mkdocs serve --dev-addr=0.0.0.0:8000"
    volumes:
      - .:/docs
    ports:
      - 8000:8000
