services:
  docs:
    image: python:3.14.5-alpine3.22@sha256:6b91e66ab2a880ce9ca5a1b91c70f45963ff71ff68268df056336e1a657d5efd
    entrypoint: [ ]
    command: sh -c "cd docs && pip install -r requirements.txt && mkdocs serve --dev-addr=0.0.0.0:8000"
    volumes:
      - .:/docs
    ports:
      - 8000:8000
