site_name: KGraphQL
site_description: KGraphQL Documentation
site_url: https://stuebingerb.github.io/KGraphQL/
dev_addr: 0.0.0.0:8000

repo_name: 'stuebingerb/KGraphQL'
repo_url: 'https://github.com/stuebingerb/KGraphQL'

docs_dir: 'content'
edit_uri: 'edit/main/docs/content'

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  custom_dir: 'theme'
  language: en
  include_sidebar: true
  # favicon
  # logo
  feature:
    tabs: false
  palette:
    - media: "(prefers-color-scheme)"
      primary: 'black'
      accent: 'blue'
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'black'
      accent: 'blue'
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'black'
      accent: 'blue'
  i18n:
    prev: 'Previous'
    next: 'Next'

extra_css:
  - assets/hljs/styles/atom-one-light.css # HightlightJS's CSS theme

extra_javascript:
  - assets/hljs/highlight.min.js # Download from https://highlightjs.org/download/
  - assets/hljs/init.js
  - assets/replace_maven_version.js

plugins:
  - search
  - exclude:
      glob:
        - "**/include-*.md"

markdown_extensions:
  - admonition
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/stuebingerb/KGraphQL

nav:
  - 'index.md'
  - 'Installation/index.md'
  - 'Examples/index.md'
  - 'Plugins/ktor.md'
  - 'Tutorials':
      - 'Tutorials/ktor.md'
      - 'Tutorials/starwars.md'
  - 'Reference':
      - 'Reference/operations.md'
      - 'Reference/configuration.md'
      - 'Reference/resolver.md'
      - 'Reference/errorHandling.md'
      - 'Reference/deprecation.md'
      - 'Reference/accessRule.md'
      - 'Type System':
          - 'Reference/Type System/overview.md'
          - 'Reference/Type System/scalars.md'
          - 'Reference/Type System/enums.md'
          - 'Reference/Type System/unions.md'
          - 'Reference/Type System/input-objects.md'
          - 'Reference/Type System/objects-and-interfaces.md'
      - 'Reference/stitching.md'
