name: Benchmarks (Base Branch)

on:
  push:
    branches:
      - main

permissions:
  checks: write

jobs:
  benchmark_base_branch:
    name: Bencher (Base Branch)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 # v5
      - name: Run benchmarks
        id: run
        run: |
          ./gradlew benchmark
          echo "result_file=$(find . -type f -name 'jvm.json')" >> $GITHUB_OUTPUT
      - uses: bencherdev/bencher@main
      - name: Track benchmark result with Bencher
        run: |
          bencher run \
          --project d1158d5b-df59-4769-9ff0-8b2fd3d648b0 \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch main \
          --testbed ubuntu-latest \
          --threshold-measure latency \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-lower-boundary _ \
          --threshold-upper-boundary 0.99 \
          --threshold-measure throughput \
          --threshold-test t_test \
          --threshold-max-sample-size 64 \
          --threshold-lower-boundary 0.99 \
          --threshold-upper-boundary _ \
          --thresholds-reset \
          --err \
          --github-actions '${{ secrets.GITHUB_TOKEN }}' \
          --adapter java_jmh --file ${{ steps.run.outputs.result_file }}
