name: Benchmarks Cleanup (Pull Request)

on:
  pull_request:
    types:
      - closed

permissions:
  contents: read

jobs:
  archive_pr_branch:
    name: Archive closed PR branch
    if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: bencherdev/bencher@ec56bb69a7f34096002ca3384d10e2f6676b063e # v0.6.7
      - name: Archive closed PR branch with Bencher
        run: |
          bencher archive \
          --project d1158d5b-df59-4769-9ff0-8b2fd3d648b0 \
          --token '${{ secrets.BENCHER_API_TOKEN }}' \
          --branch "$GITHUB_HEAD_REF"
